apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-path-retain
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
    defaultVolumeType: "local"
provisioner: rancher.io/local-path
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
properties:
  nodePath: /mnt
  pathPattern: "{{ .PVC.Namespace }}-{{ .PVC.Name }}"
