apiVersion: v1
kind: Secret
metadata:
    name: grafana-admin-credentials
data:
    admin-password: ENC[AES256_GCM,data:5tvbKWkEQG9gsg6O0Qv1c+lroCvHucVuAgfchBfXlAWU//QMaN55Jrolgq9zdcaCk3asV4utBDQ7+NjIOkMw6w==,iv:R4sgX87k0mvjHF17qd5VslhWC+FO5g2JbsxigGH3cIE=,tag:1cZmlzZmIkrNYXRdDMhGeg==,type:str]
    admin-user: ENC[AES256_GCM,data:sgoVIC/LD6Q=,iv:Ju30PlnH6ydHcif8JxzKNYmXzom9HzMmNwa9Wrq0mfM=,tag:0edBamyWIxUAlcHKWaPHUQ==,type:str]
sops:
    age:
        - recipient: age1hxvwy0vc4qr24t8wwmxs66vgz47t2rnepe9wy524v5xnk8r8mswq9gpe5l
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTUZ5Wm9UdFRBZzI5OG1I
            VHpOampaUGpkK3RodC9jV1JsUHFra0pGeldrCm5vUlZEL3MrTGR0Z3gyK2VNZSs0
            eXFwK1l2SXkyVnhFTGpzUnhYMCtuYmsKLS0tIGMvV0taY3k3eGpLbEMvMXhMYllP
            a2haellyMUwyTUZlY0RpUmZPNkQ0czQKmf8m6FfXrbuhD+6voSfCUz5zJdewS+yP
            VO2XjaNpsY7a+47OKU/ntK4xNxmhxOZ7I4xid9jOE1E0uCCQE2XwLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-07T22:39:41Z"
    mac: ENC[AES256_GCM,data:SU32Biz33y8thlPRygM0NrPQ1RbkRE4Y7nJElBOdCjEUA+GPso6SWCmn9vJA0YDZWAYjON+mp1HIwpHXnmb/em2XSJ3DoqwPo7nj6KdsGN0YJEHhQfzANlJ7z+o1uh3nZzQb+AOlnOeebvYqeNOlxq/8dhHMt+ADnzKnYe1fPFY=,iv:s9dtgWFRkdbtswy81NWbiB8NPGzcA0GyNZseR9tmhRE=,tag:oFnUMb9L6Fcv7DBsHVXgrg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
