apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: audiobookshelf
  name: audiobookshelf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: audiobookshelf
  template:
    metadata:
      labels:
        app: audiobookshelf
    spec:
      securityContext:
        fsGroup: 1000  # node group ID
        runAsUser: 1000  # node user ID
        runAsGroup: 1000  # node group ID
      containers:
        - name: audiobookshelf
          image: ghcr.io/advplyr/audiobookshelf:2.30.0
          ports:
            - containerPort: 3005
          envFrom:
            - configMapRef:
                name: audiobookshelf-cm
          volumeMounts:
            - name: data
              mountPath: /config
              subPath: audiobookshelf/config
            - name: data
              mountPath: /metadata
              subPath: audiobookshelf/metadata
            - name: data
              mountPath: /audiobooks
              subPath: audiobookshelf/audiobooks
            - name: data
              mountPath: /books
              subPath: audiobookshelf/books
            - name: data
              mountPath: /podcasts
              subPath: audiobookshelf/podcasts
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: audiobookshelf-pvc