apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - db-setup-job.yaml
  - db-setup-configmap.yaml
  - deployment.yaml
  - service.yaml
  - storage.yaml
  - configmap.yaml
  - cloudflared.yaml
  - daily-cronjob.yaml
