apiVersion: v1
kind: Service
metadata:
  name: mariadb-headless-svc
  namespace: mariadb
  labels:
    app: mariadb-headless-svc
spec:
  ports:
  - port: 3306
    name: mariadb
  selector:
    app: mariadb
  type: ClusterIP
  clusterIP: None
